### ISSUE TITLE
Pluggable report engines and (Xe)LaTeX reports for grumpy guys with air-gapped clusters.

### ISSUE THREAD

**Issue by devopsotrator** [opendistro-for-elasticsearch/kibana-reports#12]
There are some clusters out there created only for anomaly monitoring and bad news delivery. You  could find such deployments in one of those labs with one of those fancy particle accelerators or any other modern lab filed with hipsters. 

Some of administrators who runs such kind of systems dream of one simple thing. (Xe)LaTeX one report template and read it every morning for the next decade. 
Unfortunately, (as far as i can see) proposed model is missing couple of abstraction layers for such kind of reports, so my question is...

Any chances? 

P.S. sorry for ugly pic
![data_model](https://user-images.githubusercontent.com/41489515/84733296-86401500-afa6-11ea-9d7c-6f441ddfe522.png)

**Comment by zhongnansu** [comment]
This issue is moved to https://github.com/opensearch-project/dashboards-reports/issues/10
