### ISSUE TITLE
Tentative release for Kibana-reports plugin

### ISSUE THREAD

**Issue by rpotnuru** [opendistro-for-elasticsearch/kibana-reports#134]
Dear Team,

Do you have any tentative release date for kibana-reports plugin? Eagerly waiting for this.

Thank You.

**Comment by FromPAUS** [comment]
Hey team,

We really like to see kibana-reports work with security plugin. Right now in our setup, we have turned off all the security settings. I'm getting errors when I do export CSV. We really need the export features. Can anyone give me some pointers so I can try to make export work?

Thanks!

**Comment by abhishekjiitr** [comment]
This is indeed a very useful feature, are there any alternatives while we are waiting for the first release of _kibana-reports_?

**Comment by zhongnansu** [comment]
Hi guys, we are targeting a ODFE release around 12/10, along with other ODFE products.

**Comment by zhongnansu** [comment]
> Hey team,
> 
> We really like to see kibana-reports work with security plugin. Right now in our setup, we have turned on all the security settings. I'm getting errors when I do export CSV. We really need the export features. Can anyone give me some pointers so I can try to make export work?
> 
> Thanks!

We will integrate with security plugin for the release. Are you still having issues exporting csv?

**Comment by zhongnansu** [comment]
Good news, we have shipped reporting with ODFE 1.12.0, please check it out.
https://opendistro.github.io/for-elasticsearch/blog/releases/2020/12/opendistro-1-12-0-released/
