### ISSUE TITLE
Release reporting functionality for Kibana

### ISSUE THREAD

**Issue by abbashus** [opendistro-for-elasticsearch/kibana-reports#2]
Reports for Open Distro allows ‘Report Owner’ (engineers, including but not limited to developers, DevOps, IT Engineer, and IT admin) export and share reports from Kibana dashboards, saved search, alerts and visualizations. It helps automate the process of scheduling reports on an on-demand or a periodical basis (on cron schedules as well). Further, it also automates the process of exporting and sharing reports triggered for various alerts. The feature is present in the Dashboard, Discover, and Visualization tabs. Scheduled reports can be sent to (shared with) self or various stakeholders within the organization such as, including but not limited to, executives, managers, engineers (developers, DevOps, IT Engineer) in the form of pdf, hyperlinks, csv, excel via various channels such as email, slack, Amazon Chime. However, in order to export, schedule and share reports, report owners should have the necessary permissions as defined under Roles and Privileges.

**Comment by anirudha** [comment]
Released!

**Comment by zhongnansu** [comment]
https://opendistro.github.io/for-elasticsearch/blog/releases/2020/12/opendistro-1-12-0-released/
