### ISSUE TITLE
Plugin build scripts question

### ISSUE THREAD

**Issue by 8wlgns** [opendistro-for-elasticsearch/kibana-reports#201]
Hello? 

I tried to modify this code and yarn build then plugin-install to Kibana 7.9
But, when I plugin install zip file to Kibana then, it occurs 404 error :-(
And this zip has no target folder also.. ex) plugins/kibana-reports/target

How could I re-build including target folder for modifying source code ?
Is there any build scripts ?

**Comment by zhongnansu** [comment]
Our latest code is maintained in dev branch. Are you pulling code from there? the target folder is added into the github repo manually by us. Because for 7.9, Kibana fails to handle that. However they did in 7.10, which we will soon upgrade to. You'll find a pending PR I posted for 7.10. #205
