### ISSUE TITLE
Set up github action workflow for CI/CD

### ISSUE THREAD

**Issue by zhongnansu** [opendistro-for-elasticsearch/kibana-reports#24]
- [x] kibana-reports plugin
- [x] reports-scheduler plugin

**Comment by fastlorenzo** [comment]
@zhongnansu I have a kibana plugin as well and I'm looking at how to automate build with github action workflow, could you let me know if you find an easy way to do it. I'll do the same! cheers

**Comment by zhongnansu** [comment]
@fastlorenzo Hi, please refer to this PR #159 . FYI, this is only for kibana-reports plugin, we'll add github action for reports-scheduler later.

**Comment by fastlorenzo** [comment]
thanks, the `/target` note helped a lot!

FYI my build process is here: https://github.com/fastlorenzo/redelk-kibana-app/blob/main/.github/workflows/build.yml

**Comment by zhongnansu** [comment]
@fastlorenzo No problem. There was a minor fix in this PR https://github.com/opendistro-for-elasticsearch/kibana-reports/pull/163, so that snapshot testing can pass github action CI
