### ISSUE TITLE
Report Generation from Default Metricbeat Dashboards does not work.

### ISSUE THREAD

**Issue by DrBautze** [opendistro-for-elasticsearch/kibana-reports#250]
## Versions:
* ODFE 1.12.0
* Metricbeat 7.10.0

## Issue: 
Report generation fails with error message "invalid relative url"

## Steps to reproduce:
Install the default metricbeat dashboards in Kibana ("./metricbeat setup --dashboards") and try to generate any report (e.g.: "[Metricbeat System] Overview ECS".

## Description

After clicking on Reporting -> Download PDF, an error message occurs:
<img width="480" alt="Query_url" src="https://user-images.githubusercontent.com/55985158/102231016-cd737800-3eed-11eb-9890-e0c7e549209e.PNG">

This is the request:
<img width="484" alt="Not_working_Request" src="https://user-images.githubusercontent.com/55985158/102231055-d6644980-3eed-11eb-8c61-dac81c3a76e4.PNG">

For comparison, this is a request that works:
<img width="481" alt="working_request" src="https://user-images.githubusercontent.com/55985158/102231125-ea0fb000-3eed-11eb-83fd-4414d4817900.PNG">

Kibana logs the following errors:
```
{"type":"log","@timestamp":"2020-12-15T10:24:33Z","tags":["error","plugins","opendistroReportsKibana"],"pid":1,"message":"Failed input validation for create report Error: [query_url]: invalid relative url: /app/dashboards#/view/Metricbeat-system-overview-ecs?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-12-15T10:09:33.104Z',to:'2020-12-15T10:24:33.105Z'))&_a=(description:'Overview%20of%20system%20metrics',filters:!(),fullScreenMode:!f,options:(darkTheme:!f),query:(language:kuery,query:''),timeRestore:!f,title:'%5BMetricbeat%20System%5D%20Overview%20ECS',viewMode:view)"}
```

## Workaround:
Cloning the dashboard and saving with another name has resolved the issue in one case. I did not test the workaround much further. 

## Remark
It looks like the issue comes from the specific name of the dashboard "Metricbeat-system-overview-ecs" while IDs like "edf84fe0-e1a0-11e7-b6d5-4dc382ef7f5b" seem to work. This is however a guess and might not be related.

**Comment by zhongnansu** [comment]
ref: https://demo.elastic.co/app/dashboards#/view/Metricbeat-system-overview-ecs?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(description:'Overview%20of%20system%20metrics',filters:!(),fullScreenMode:!f,options:(darkTheme:!f),query:(language:kuery,query:''),timeRestore:!f,title:'%5BMetricbeat%20System%5D%20Overview%20ECS',viewMode:view)
