### ISSUE TITLE
Visual reports fails generation on custom dashboard ids

### ISSUE THREAD

**Issue by jasonrojas** [opendistro-for-elasticsearch/kibana-reports#252]
`{"type":"log","@timestamp":"2020-12-15T20:37:53Z","tags":["error","plugins","opendistroReportsKibana"],"pid":30777,"message":"Failed input validation for create report definition Error: [report_params.core_params.base_url]: invalid relative url: /app/dashboards#/view/AWCUqesWib22Ai8JwW3u"}
`

Happens when I try to create a report. Permissions for accessing the reporting indices and such are all there. This only happens when I try to generate the report.

**Comment by jasonrojas** [comment]
Looks like if I create a brand new dashboard its OK and I can create a report off of that. However dashboards I have had for months, created many versions ago, trigger the same error when trying to create a report.

**Comment by jasonrojas** [comment]
Looks like it is coming down to the dasboard id of the saved object:

AWCUqesWib22Ai8JwW3u is the dashboard I am trying to report on, I cloned it, which generated a new id: f9793f90-3f18-11eb-b520-533ece4aa0d8, the new cloned dashboard

**Comment by anirudha** [comment]
can you paste info on the security access controls here, this feel like an access issue or permissions issue not a bug. can you add more info to this ticket

**Comment by jasonrojas** [comment]
Security is not the issue, once I created the test dashboard today and generated a report where everything worked, indexes were created properly etc so I ruled out permissions there.
Here is the saved object of the dashboard that doesnt work:

`{
id: "AWCUqesWib22Ai8JwW3u",
type: "dashboard",
namespaces: [
"default"
],
updated_at: "2020-12-15T21:02:47.265Z",
version: "WzIzNDQsMV0=",
attributes: {
title: "Broken dashboard",
hits: 0,
description: "",
panelsJSON: "[ { "version": "7.10.0", "gridData": { "h": 30, "i": "20", "w": 8, "x": 40, "y": 15 }, "panelIndex": "20", "embeddableConfig": { "vis": { "params": { "sort": { "columnIndex": null, "direction": null } } } }, "panelRefName": "panel_0" }, { "version": "7.10.0", "gridData": { "h": 30, "i": "21", "w": 12, "x": 0, "y": 35 }, "panelIndex": "21", "embeddableConfig": { "vis": { "params": { "sort": { "columnIndex": 0, "direction": "desc" } } } }, "panelRefName": "panel_1" }, { "version": "7.10.0", "gridData": { "h": 30, "i": "27", "w": 12, "x": 12, "y": 35 }, "panelIndex": "27", "embeddableConfig": { "vis": { "params": { "sort": { "columnIndex": null, "direction": null } } } }, "panelRefName": "panel_2" }, { "version": "7.10.0", "gridData": { "h": 30, "i": "28", "w": 8, "x": 32, "y": 15 }, "panelIndex": "28", "embeddableConfig": { "vis": { "params": { "sort": { "columnIndex": 0, "direction": "desc" } } } }, "panelRefName": "panel_3" }, { "version": "7.10.0", "gridData": { "h": 15, "i": "30", "w": 8, "x": 40, "y": 0 }, "panelIndex": "30", "embeddableConfig": { "vis": { "params": { "sort": { "columnIndex": null, "direction": null } } } }, "panelRefName": "panel_4" }, { "version": "7.10.0", "gridData": { "h": 20, "i": "31", "w": 8, "x": 24, "y": 35 }, "panelIndex": "31", "embeddableConfig": { "vis": { "params": { "sort": { "columnIndex": null, "direction": null } } } }, "panelRefName": "panel_5" }, { "version": "7.10.0", "gridData": { "h": 10, "i": "37", "w": 16, "x": 16, "y": 25 }, "panelIndex": "37", "embeddableConfig": {}, "panelRefName": "panel_6" }, { "version": "7.10.0", "gridData": { "h": 10, "i": "39", "w": 16, "x": 16, "y": 15 }, "panelIndex": "39", "embeddableConfig": {}, "panelRefName": "panel_7" }, { "version": "7.10.0", "gridData": { "h": 20, "i": "46", "w": 16, "x": 0, "y": 15 }, "panelIndex": "46", "embeddableConfig": { "vis": { "legendOpen": true } }, "panelRefName": "panel_8" }, { "version": "7.10.0", "gridData": { "h": 15, "i": "47", "w": 9, "x": 30, "y": 0 }, "panelIndex": "47", "embeddableConfig": { "vis": { "defaultColors": { "0 - 50": "rgb(247,252,245)", "50 - 100": "rgb(0,68,27)" }, "legendOpen": false } }, "panelRefName": "panel_9" }, { "version": "7.10.0", "gridData": { "h": 15, "i": "48", "w": 10, "x": 0, "y": 0 }, "panelIndex": "48", "embeddableConfig": { "vis": { "defaultColors": { "0 - 10": "rgb(255,245,240)", "10 - 20": "rgb(103,0,13)" }, "legendOpen": false } }, "panelRefName": "panel_10" }, { "version": "7.10.0", "gridData": { "h": 15, "i": "50", "w": 10, "x": 20, "y": 0 }, "panelIndex": "50", "embeddableConfig": { "vis": { "colors": { "0 - 10": "#E5AC0E" }, "defaultColors": { "0 - 10": "rgb(8,48,107)" }, "legendOpen": false } }, "panelRefName": "panel_11" }, { "version": "7.10.0", "gridData": { "h": 15, "i": "51", "w": 10, "x": 10, "y": 0 }, "panelIndex": "51", "embeddableConfig": {}, "panelRefName": "panel_12" }, { "version": "7.10.0", "gridData": { "x": 0, "y": 65, "w": 48, "h": 30, "i": "5c9ad49e-4a00-465b-bbeb-8df6f33bab8c" }, "panelIndex": "5c9ad49e-4a00-465b-bbeb-8df6f33bab8c", "embeddableConfig": {}, "panelRefName": "panel_13" } ]",
optionsJSON: "{ "darkTheme": false, "useMargins": false }",
version: 1,
timeRestore: false,
kibanaSavedObjectMeta: {
searchSourceJSON: "{ "query": { "query": "", "language": "kuery" }, "filter": [] }"
}
},
references: [
{
name: "panel_0",
id: "995e2280-3df3-11e7-a44e-c79ca8efb780",
type: "visualization"
},
{
name: "panel_1",
id: "852816e0-3eb1-11e7-90cb-918f9cb01e3d",
type: "visualization"
},
{
name: "panel_2",
id: "297df800-3f7e-11e7-bd24-6903e3283192",
type: "visualization"
},
{
name: "panel_3",
id: "35b6d320-3f7f-11e7-bd24-6903e3283192",
type: "visualization"
},
{
name: "panel_4",
id: "471a3580-3f6b-11e7-88e7-df1abe6547fb",
type: "visualization"
},
{
name: "panel_5",
id: "de1a5f40-3f85-11e7-97f9-3777d794626d",
type: "visualization"
},
{
name: "panel_6",
id: "5093c620-44e9-11e7-8014-ede06a7e69f8",
type: "visualization"
},
{
name: "panel_7",
id: "fb6eb020-49ab-11e7-8f8c-57ad64ec48a6",
type: "visualization"
},
{
name: "panel_8",
id: "56f0f5f0-3ebe-11e7-a192-93f36fbd9d05",
type: "visualization"
},
{
name: "panel_9",
id: "e6b5b920-f77a-11e8-8f42-af2e41422cf8",
type: "visualization"
},
{
name: "panel_10",
id: "8c9c9430-f77b-11e8-8f42-af2e41422cf8",
type: "visualization"
},
{
name: "panel_11",
id: "61b43c00-f77b-11e8-8f42-af2e41422cf8",
type: "visualization"
},
{
name: "panel_12",
id: "c533c120-fe8c-11e8-8f42-af2e41422cf8",
type: "visualization"
},
{
name: "panel_13",
id: "54648700-3f74-11e7-852e-69207a3d0726",
type: "search"
}
],
migrationVersion: {
dashboard: "7.9.3"
}
}`

And here is the dashboard that does work (clone of the above dashboard):

`{
id: "f9793f90-3f18-11eb-b520-533ece4aa0d8",
type: "dashboard",
namespaces: [
"default"
],
updated_at: "2020-12-15T21:03:26.216Z",
version: "WzIzNTQsMV0=",
attributes: {
title: "Working Dashboard",
hits: 0,
description: "",
panelsJSON: "[{"version":"7.10.0","gridData":{"h":30,"i":"20","w":8,"x":40,"y":15},"panelIndex":"20","embeddableConfig":{"vis":{"params":{"sort":{"columnIndex":null,"direction":null}}}},"panelRefName":"panel_0"},{"version":"7.10.0","gridData":{"h":30,"i":"21","w":12,"x":0,"y":35},"panelIndex":"21","embeddableConfig":{"vis":{"params":{"sort":{"columnIndex":0,"direction":"desc"}}}},"panelRefName":"panel_1"},{"version":"7.10.0","gridData":{"h":30,"i":"27","w":12,"x":12,"y":35},"panelIndex":"27","embeddableConfig":{"vis":{"params":{"sort":{"columnIndex":null,"direction":null}}}},"panelRefName":"panel_2"},{"version":"7.10.0","gridData":{"h":30,"i":"28","w":8,"x":32,"y":15},"panelIndex":"28","embeddableConfig":{"vis":{"params":{"sort":{"columnIndex":0,"direction":"desc"}}}},"panelRefName":"panel_3"},{"version":"7.10.0","gridData":{"h":15,"i":"30","w":8,"x":40,"y":0},"panelIndex":"30","embeddableConfig":{"vis":{"params":{"sort":{"columnIndex":null,"direction":null}}}},"panelRefName":"panel_4"},{"version":"7.10.0","gridData":{"h":20,"i":"31","w":8,"x":24,"y":35},"panelIndex":"31","embeddableConfig":{"vis":{"params":{"sort":{"columnIndex":null,"direction":null}}}},"panelRefName":"panel_5"},{"version":"7.10.0","gridData":{"h":10,"i":"37","w":16,"x":16,"y":25},"panelIndex":"37","embeddableConfig":{},"panelRefName":"panel_6"},{"version":"7.10.0","gridData":{"h":10,"i":"39","w":16,"x":16,"y":15},"panelIndex":"39","embeddableConfig":{},"panelRefName":"panel_7"},{"version":"7.10.0","gridData":{"h":20,"i":"46","w":16,"x":0,"y":15},"panelIndex":"46","embeddableConfig":{"vis":{"legendOpen":true}},"panelRefName":"panel_8"},{"version":"7.10.0","gridData":{"h":15,"i":"47","w":9,"x":30,"y":0},"panelIndex":"47","embeddableConfig":{"vis":{"defaultColors":{"0 - 50":"rgb(247,252,245)","50 - 100":"rgb(0,68,27)"},"legendOpen":false}},"panelRefName":"panel_9"},{"version":"7.10.0","gridData":{"h":15,"i":"48","w":10,"x":0,"y":0},"panelIndex":"48","embeddableConfig":{"vis":{"defaultColors":{"0 - 10":"rgb(255,245,240)","10 - 20":"rgb(103,0,13)"},"legendOpen":false}},"panelRefName":"panel_10"},{"version":"7.10.0","gridData":{"h":15,"i":"50","w":10,"x":20,"y":0},"panelIndex":"50","embeddableConfig":{"vis":{"colors":{"0 - 10":"#E5AC0E"},"defaultColors":{"0 - 10":"rgb(8,48,107)"},"legendOpen":false}},"panelRefName":"panel_11"},{"version":"7.10.0","gridData":{"h":15,"i":"51","w":10,"x":10,"y":0},"panelIndex":"51","embeddableConfig":{},"panelRefName":"panel_12"},{"version":"7.10.0","gridData":{"x":0,"y":65,"w":48,"h":30,"i":"5c9ad49e-4a00-465b-bbeb-8df6f33bab8c"},"panelIndex":"5c9ad49e-4a00-465b-bbeb-8df6f33bab8c","embeddableConfig":{},"panelRefName":"panel_13"}]",
optionsJSON: "{"darkTheme":false,"useMargins":false}",
version: 1,
timeRestore: false,
kibanaSavedObjectMeta: {
searchSourceJSON: "{"query":{"query":"","language":"kuery"},"filter":[]}"
}
},
references: [
{
name: "panel_0",
type: "visualization",
id: "995e2280-3df3-11e7-a44e-c79ca8efb780"
},
{
name: "panel_1",
type: "visualization",
id: "852816e0-3eb1-11e7-90cb-918f9cb01e3d"
},
{
name: "panel_2",
type: "visualization",
id: "297df800-3f7e-11e7-bd24-6903e3283192"
},
{
name: "panel_3",
type: "visualization",
id: "35b6d320-3f7f-11e7-bd24-6903e3283192"
},
{
name: "panel_4",
type: "visualization",
id: "471a3580-3f6b-11e7-88e7-df1abe6547fb"
},
{
name: "panel_5",
type: "visualization",
id: "de1a5f40-3f85-11e7-97f9-3777d794626d"
},
{
name: "panel_6",
type: "visualization",
id: "5093c620-44e9-11e7-8014-ede06a7e69f8"
},
{
name: "panel_7",
type: "visualization",
id: "fb6eb020-49ab-11e7-8f8c-57ad64ec48a6"
},
{
name: "panel_8",
type: "visualization",
id: "56f0f5f0-3ebe-11e7-a192-93f36fbd9d05"
},
{
name: "panel_9",
type: "visualization",
id: "e6b5b920-f77a-11e8-8f42-af2e41422cf8"
},
{
name: "panel_10",
type: "visualization",
id: "8c9c9430-f77b-11e8-8f42-af2e41422cf8"
},
{
name: "panel_11",
type: "visualization",
id: "61b43c00-f77b-11e8-8f42-af2e41422cf8"
},
{
name: "panel_12",
type: "visualization",
id: "c533c120-fe8c-11e8-8f42-af2e41422cf8"
},
{
name: "panel_13",
type: "search",
id: "54648700-3f74-11e7-852e-69207a3d0726"
}
],
migrationVersion: {
dashboard: "7.9.3"
}
}`

**Comment by jasonrojas** [comment]
Looks like this validator does not validate the old dashboard id's:
https://github.com/opendistro-for-elasticsearch/kibana-reports/blob/8b6241eed637837c18703ea58f6f879a569a1bc1/kibana-reports/server/utils/validationHelper.ts#L18-L35

I tested the regex to verify.
<img width="1661" alt="Screen Shot 2020-12-15 at 4 58 19 PM" src="https://user-images.githubusercontent.com/158399/102290919-d0bf3180-3ef6-11eb-8429-300d01617f69.png">

**Comment by DrBautze** [comment]
Looks exactly like my problem: https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/250

**Comment by zhongnansu** [comment]
@jasonrojas You are right, the validator verifies the uuid format exactly as the regex in the screenshot shows. Since our plugin start developing from Kibana 7.9.1 We are not aware of this id format change in the past, and will look into it. Thanks for your feedback as well. @nosferatu314

**Comment by jasonrojas** [comment]
Just to make sure I add the work-around for anyone that also runs into this issue. If you clone the dashboard or saved search you are trying to report on it should generate a new id for the resource and that will work with the reporting until this and #250 are closed.

**Comment by zhongnansu** [comment]
Found something from Kibana community. https://github.com/elastic/kibana/issues/11338
Human readable dashboard ids should be abandoned, not sure why Metricbeats dashboard is still using it. @nosferatu314 #250 

Also, what version of Kibana and ES that you are using, which generates this id format `AWCUqesWib22Ai8JwW3u` @jasonrojas

**Comment by remioo** [comment]
Hello.

I have the same issue, with a dashboard with a custom id:
{"type":"log","@timestamp":"2020-12-18T01:18:44Z","tags":["error","plugins","opendistroReportsKibana"],"pid":1,"message":"Failed input validation for create report definition Error: [report_params.core_params.base_url]: invalid relative url: **/app/dashboards#/view/bks400-overview**"}

**Comment by zhongnansu** [comment]
@remioo Thanks for the feed back. Can you share how that dashboard is created? Or did you create the custom saved_object id? I just tried to figure out why other formats of id can be created. Because the dashboard created by kibana should have one format of uuid, that's what our validators in the code is targeting.

**Comment by remioo** [comment]
Indeed I created the custom id with the saved object method.
Is there any specific reason why you need to be so restrictive in the regex?

**Comment by zhongnansu** [comment]
> Indeed I created the custom id with the saved object method.
> Is there any specific reason why you need to be so restrictive in the regex?

Yes, it's all about secuirty concern. Since the create report API asks for the relative url as input, there is an SSRF(Server-side request forgery) vulnerability. Assume if someone finds an open redirect vulnerability, he can pass in `/app/dashboards#/view/anything?nextUrl=https://attacker-controlled-domain.com
 `

**Comment by remioo** [comment]
I see, thank you for your answer.
And what about having the regex changed from [a-f0-9-]+ to [a-zA-Z0-9-]+ 
Or maybe having a setting to tune it?
This would still prevent the vulnerability and enable both the old IDs use case and custom IDs one (with restrictions on the characters)

**Comment by zhongnansu** [comment]
> I see, thank you for your answer.
> And what about having the regex changed from [a-f0-9-]+ to [a-zA-Z0-9-]+
> Or maybe having a setting to tune it?
> This would still prevent the vulnerability and enable both the old IDs use case and custom IDs one (with restrictions on the characters)

Yes, relax the regex was the first thing that came to my mind, but even `[a-zA-Z0-9-]+` we are still not allowing anything, but allowing more than standard UUID, I feel like it's not a generic solution. In Kibana, how `saved_object` ids are created is either custom value or default value(uuid). So the solution may be relax the regex to accept anything, we are still assessing the security concern. Will update the thread once we have a solution.
