### ISSUE TITLE
Missing standalone plugin endpoint mentioned in documentation

### ISSUE THREAD

**Issue by shobhitsinghal624** [opendistro-for-elasticsearch/kibana-reports#254]
The [url endpoint](https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugin/opendistro-reports/linux/x64/opendistroReportsKibana-1.12.0.0.zip) mentioned in the [documentation](https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/plugins/#reports-kibana) returns the CloudFront standard access denied message:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>6PEH5T2M7N4Y0QCR</RequestId>
<HostId>d3BBWWh9O57tSoygMvkoyEAcBHDlFgzClSZkoKS1JXkG0mEbXW42pJ8c2adWhItNSctKGq8CM7o=</HostId>
</Error>
```

**Comment by shobhitsinghal624** [comment]
There seems to be a typo in the documentation. Created a PR for the fix.

**Comment by zhongnansu** [comment]
Thx for the fix
