### ISSUE TITLE
Error loading report definitions table

### ISSUE THREAD

**Issue by shobhitsinghal624** [opendistro-for-elasticsearch/kibana-reports#255]
I did a standalone plugin install on a fresh docker install of Elasticsearch 7.10.0 + Kibana 7.10.0. 

Getting this error when I navigate to the reporting page:
```
Error loading report definitions table.

Insufficient permissions. Reach out to your Kibana administrator.
```

Kibana logs show this error:
```
{"type":"log","@timestamp":"2020-12-16T06:49:39Z","tags":["error","plugins","opendistroReportsKibana"],"pid":7,"message":"Failed to get reports details: [security_exception] action [indices:admin/create] is unauthorized for user [_system] :: {\"path\":\"/_opendistro/_reports/instances\",\"query\":{\"maxItems\":10000},\"statusCode\":403,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"action [indices:admin/create] is unauthorized for user [_system]\\\"}],\\\"type\\\":\\\"security_exception\\\",\\\"reason\\\":\\\"action [indices:admin/create] is unauthorized for user [_system]\\\"},\\\"status\\\":403}\"}"}
```

Is there some permission that I need to add manually?

**Comment by zhongnansu** [comment]
Hi, do you have both reports-scheduler and kibana-reports plugin installed when you said you did a standalone plugin install?

**Comment by shobhitsinghal624** [comment]
I have installed these plugins on elasticsearch:

- opendistro-reports-scheduler    1.12.0.0
- opendistro-job-scheduler        1.12.0.0

and this plugin on kibana:

- opendistroReportsKibana           1.12.0.0

**Comment by zhongnansu** [comment]
@akbhatta Can you help here?

**Comment by akbhatta** [comment]
The error "action [indices:admin/create] is unauthorized for user [_system]" is from security plugin. Will check further.

@hardik-k-shah @vrozov Let me know if you have any info on this.

**Comment by vrozov** [comment]
@akbhatta There is a request to create an index that is denied due to insufficient permission.

**Comment by zhongnansu** [comment]
Is this resolved?
