### ISSUE TITLE
Create report definition: dashboard list limited to 10 

### ISSUE THREAD

**Issue by remioo** [opendistro-for-elasticsearch/kibana-reports#264]
Version: opendistro 1.12 - docker image

Step to reproduce:
- create more that 10 dashboards
- in reports create a new definition
- the 'Select dashboard' listbox only contains 10 dashboards (and is not a searchable list box)

Bonus: Visualization listbox is fine, but it would be nice to have a searchable box: I have almost 400 visualizations so it can take time to find the right one

**Comment by davidcui1225** [comment]
Dashboard listbox limit has been removed
