### ISSUE TITLE
Out of memory error with new plugin

### ISSUE THREAD

**Issue by brian-grabau** [opendistro-for-elasticsearch/kibana-reports#265]
We noticed a lot of our of memory failures in Kibana when users trying to create reports. Even though reports don't work; do to index patens we use, which I think was identified in other issue reports.  Is there any recommendations for increasing memory cash size in Kibana?

**Comment by anirudha** [comment]
could you please add more detail on how to reproduce or details on your setup ? thanks

**Comment by brian-grabau** [comment]
This may be due to size of our deployment and number of users we have, looks like issue predated the reports plugin, but, issue is observed when user attempts to generate report and prior to update kibana failed gracefully and restarted, now we observe the if Kibana fails it does not always reconnect to Azure AD. Reconnect issue was resolved by restarting both Kibana + Elastic coordinating node also running on Kibana node. We also have increased memory assigned to Kibana process and have remove access to reporting plugin for all users until the bug is resolved where reporting plugin does not support index patterns until fix is released
