### ISSUE TITLE
Cannot create any reports

### ISSUE THREAD

**Issue by antonisnyc94** [opendistro-for-elasticsearch/kibana-reports#273]
Whenever I am trying to create a report firstly i get the first error and then when I try again Im getting a different error which states that Name must not be empty, which it is not empty. Kibana logs dont really show anything, neither elasticsearch. How can I investigate further?

![image](https://user-images.githubusercontent.com/36517441/102842292-9eb93e00-43d4-11eb-90d4-4b00a7207fd9.png)

![image](https://user-images.githubusercontent.com/36517441/102842363-cdcfaf80-43d4-11eb-906c-01b8f690895a.png)

thanks!
Tony

**Comment by zhongnansu** [comment]
@antonisnyc94 If there isn't any log in Kibana side, which means the request never get sent from client. It looks to me it fails the client side input validation. But from your screenshot, it looks like you have the correct format for "Name".

**Comment by zhongnansu** [comment]
@davidcui-amzn any idea how to find the root cause?

**Comment by davidcui1225** [comment]
Will look- this name should not violate any client-side validation

**Comment by zhongnansu** [comment]
@antonisnyc94 could you share more details about how we can reproduce the issue? Is there any log for the first issue you met? "Error create report definition"

**Comment by davidcui1225** [comment]
+1 as above, I cannot reproduce this issue locally as of now

**Comment by antonisnyc94** [comment]
Hey guys, it appears that for some reason the reporting package was missing in the 2 out of the 3 nodes in elasticsearch. I installed it and now everything is fine.

Thanks,
Tony
