### ISSUE TITLE
Reports not working when "server.basePath" property present

### ISSUE THREAD

**Issue by vinaykumar4s** [opendistro-for-elasticsearch/kibana-reports#278]
Kibana reports not working when "server.basePath" property present in kibana.yml

##
kibana.yml

server.basePath: "/insights"
server.rewriteBasePath: true
##

Version details:

kibana version 7.10.0
reports plugin version  1.12.0.0
elasticsearch  version 7.10.0
##

https://github.com/vinaykumar4s/issues/blob/main/reports-error.png
![image](https://user-images.githubusercontent.com/25397819/103107947-17a4d980-4611-11eb-97d6-2cdd092b0e30.png)

https://github.com/vinaykumar4s/issues/blob/main/reports-error1.png
![image](https://user-images.githubusercontent.com/25397819/103107965-2c816d00-4611-11eb-8db4-90ad1af08f50.png)

**Comment by joshuali925** [comment]
Hi, this is a known issue with upstream Kibana new plugin platform, that plugins are unable to read all configurations from `kibana.yml`. We are tracking it in issue #98 and working on alternative solutions.

Thanks

**Comment by vinaykumar4s** [comment]
@joshuali925 Thank you i will close this now.
