### ISSUE TITLE
security_tenant and embed parameteres are mutually exclusive 

### ISSUE THREAD

**Issue by WassimDhib** [opendistro-for-elasticsearch/kibana-reports#279]
Hi

In my application, I embed Kibana dashboards and other pages in iframes.

In order to select tenant, we add security_tenant parameter to the url (before the # anchor)
To embed the Kibana page (remove the upper and leftside menus), we use embed=true (after the # anchor)

Each of those parameters works separately, but when we put them together the embed parameter is not working

Here is a sample of url in iframe 

`https://kibana_host:443/app/opendistro_kibana_reports?security_tenant=my-tenant#/?embed=true`

**Comment by zhongnansu** [comment]
The issue has been moved to https://github.com/opensearch-project/dashboards-reports/issues/14
