### ISSUE TITLE
Support for Powerpoint Reports from Kibana Dashboards

### ISSUE THREAD

**Issue by sammad** [opendistro-for-elasticsearch/kibana-reports#31]
Hello, 

Kibana dashboards when used with customers over API health metrics, often after the workshop customers expect a report.  If user can download one's visualizations as powerpoint presentation with graphs backed by actual data. It empowers user to tweak the scale of data, change legends etc before sending the report to the stakeholders. It would be a powerful feature to include powerpoint plugin in Kibana reports

**Comment by zhongnansu** [comment]
This issue is moved to https://github.com/opensearch-project/dashboards-reports/issues/11
