### ISSUE TITLE
Include all fields in the document to the generated CSV from saved search

### ISSUE THREAD

**Issue by kaustubhkhare** [opendistro-for-elasticsearch/kibana-reports#320]
It would be great if the reports plugin could add all the fields present in the document to the csv instead of just the fields added to grid.

**Comment by zhongnansu** [comment]
Hi could you be more specific? It's better that you provide some screenshots and steps, so that we can better understand. Thanks!

**Comment by zhongnansu** [comment]
no reply, closing
