### ISSUE TITLE
Allow saved search included in a dashboard to be exported to csv individually

### ISSUE THREAD

**Issue by kaustubhkhare** [opendistro-for-elasticsearch/kibana-reports#321]
We can't export an individual csv which is included in a dashboard.
Saved searches can only be exported from the discover tab.

**Comment by zhongnansu** [comment]
same as #326

**Comment by zhongnansu** [comment]
same as https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/326, closing for clear tracking
