### ISSUE TITLE
PDF Report Size / Table Size (currently limited to 23 Entries?)

### ISSUE THREAD

**Issue by uplexPaul** [opendistro-for-elasticsearch/kibana-reports#326]
I've been trying out the report feature in the past week and got it finally working.

Then i tried to generate some pdf reports. I tried reporting a dashboard and a visualization including a data table showing some top accessed urls from a webserver.

Problem is that the resulting Report pdf Height seems to be limited somehow. The pdf is only showing the first 23 Entries of the data table and i don't see any option anywhere to change that size. I do need the last 50 Entries to be included in that Report.

Is there any option to increase the max shown size? Do i need to increase some resolution of the chromium-headless-browser or is the limit somewhere else? Or will this not work at all and do i need to use csv exports for achieving my top list?

Thank you very much for building this nice reporting feature so far.
Any help on this would be really appreciated.

**Comment by zhongnansu** [comment]
Hi thanks for using our product and sharing feedback. Currently the visual report is limited to show whatever you saw when you click to open one dashboard, you can think of it as a "screenshot" of that dashboard page. Does the table on your dashboard page by default show the last 50 entries you want? If you resize your brower window, does it give more entries from the table, if not, then pdf will also not be able to show that.

The workarounds are 
1. save that table as a saved search and use csv report as you mentioned. We are still investigating a proper way to enable export table from dashboard. We'd love to hear from you on the best user experience you expect.
2. edit the dashboard to display the entries you want and save the dashboard, then download as pdf again

**Comment by zhongnansu** [comment]
similar to opensearch-project/reporting#321

**Comment by kgcreative** [comment]
There seems to be two related issues here.

1) The height of the table in the export doesn't capture the full size of the table pagination, so it gets cut off at the scroll.

2) The data in the table is not exportable individually.

@zhongnansu – Maybe we can find a way of at least changing the table height in the exported view to show the full table, instead of overflowing it?

**Comment by uplexPaul** [comment]
@zhongnansu Yes you're right i actually get what i see on my screen in the pdf. But on the dashboard i can click on "maximize table" which shows all entries of the table and disables scrolling on it. Thats not available for the report at all.

I just tried your workaround. I've saved the table as a saved search. I can see that and some other saved searches when i browse throughn kibana. But when i try to create a report definition for the saved search, it always shows me "There aren't any options available" - so it seems like it can't get the list of saved searches. I am not able to select the saved search for creating a report definition. And directly klicking the "Export to PDF" doesn't work at all and always just quits with an error.

**Comment by uplexPaul** [comment]
@zhongnansu I am actually able to create a report definition for a saved search which was saved from the "Discover"-Tab of Kibana. But i can't do any grouping or smth. else there - So it is completely useless for me to report the RAW data into csv.

**Comment by zhongnansu** [comment]
This issue has been moved to https://github.com/opensearch-project/dashboards-reports/issues/15
