### ISSUE TITLE
Report empty if using plugins with client side calculations

### ISSUE THREAD

**Issue by itbm** [opendistro-for-elasticsearch/kibana-reports#330]
When using plugins that do client side calculations, such as Kibana Enhanced Table, reports are empty as the screenshot is taken before the page has fully rendered.

**Comment by anirudha** [comment]
Could you please add an image or more description￼

**Comment by itbm** [comment]
Sure, the report generates from a dashboard but is blank where the plugin should be. Adding a wait before the screenshot gives it enough time to render and exports correctly.

![image](https://user-images.githubusercontent.com/22393016/108767632-8c7f8b80-754e-11eb-8a56-53ba5b0f0194.png)
