### ISSUE TITLE
Reporting behind Reverse Proxy

### ISSUE THREAD

**Issue by ky-ma** [opendistro-for-elasticsearch/kibana-reports#332]
I can't generate any reports and I believe it has to do with the reverse Proxy setting. The headless chrome that launches isn't communicating back through the proxy port and or path. There doesn't seem to be a setting specific to the kibana report like there is for the main kibana setting from elasticsearch.

Is there a method to get this to work right now on a reverse proxy?

Thanks!

**Comment by gaiksaya** [comment]
Hi @zhongnansu I believe this issue is related to kibana reports hence transferring this issue to kibana-reports repo. 
Please take a look.
Thanks!

**Comment by zhongnansu** [comment]
@gaiksaya Thx, this is a reporting issue, we'll looking into this

**Comment by zhongnansu** [comment]
@ky-ma There is an existing issue related to reverse proxy. Is this the same issue as yours? https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/328. Besides, there is a pending PR there. We are still evaluating the issue and will deliver a fix soon

**Comment by ky-ma** [comment]
HI @zhongnansu,

I think it's similar, but slightly different I'm not using authentication. It's just a different URL Path (the reverse proxy URL) that the chrome headless doesn't know.

**Comment by ky-ma** [comment]
Hi @zhongnansu  do you have a work around for this issue to get me going for now? thanks!

**Comment by zhongnansu** [comment]
@ky-ma Hi, could you take a look at this issue, is it related to yours? If you set `server.rewriteBasePath = true`, does it work? https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/333

**Comment by ky-ma** [comment]
Where is the file that I need to add the config to?

**Comment by zhongnansu** [comment]
> Where is the file that I need to add the config to?

It should be in `kibana/config/kibana.yml`

**Comment by ky-ma** [comment]
OK, I have that already set, that's how Kibana works for me behind the proxt.

That setting doesn't work for the headless chrome that launches in the back ground for report generation though.

**Comment by ky-ma** [comment]
Hi @zhongnansu,

Do you have any updates to this? A work around for now?

Thanks!

**Comment by zhongnansu** [comment]
This issue has been moved to https://github.com/opensearch-project/dashboards-reports/issues/16
