### ISSUE TITLE
reverse proxy rewrite rules break pdf/png report generation

### ISSUE THREAD

**Issue by ccottam** [opendistro-for-elasticsearch/kibana-reports#333]
The current default behaviour for kibana (due to change with version 8), is that if you configure the server.basepath, then you also need to configure your reverse proxy to rewrite the url to remove the basepath.
This behaviour is configurable from 6.3 (via server.rewriteBasePath) but the default behaviour still assumes the proxy is rewriting the url.

(quote from the 5.6 docs as they do a better job of explaining it than later versions) 
```
server.basePath:
    Enables you to specify a path to mount Kibana at if you are running behind a proxy. This only affects the URLs generated by Kibana, your proxy is expected to remove the basePath value before forwarding requests to Kibana.
```

https://github.com/opendistro-for-elasticsearch/kibana-reports/pull/313 works only if the server.rewriteBasePath is set to true, which isn't the default configuration

Otherwise chromium makes a request to http://0:5601/basepath/app/visualize... and gets a 404.

**Comment by ccottam** [comment]
I tried modifying the relativeUrl code to strip the basepath
https://github.com/opendistro-for-elasticsearch/kibana-reports/blob/dev/kibana-reports/server/routes/lib/createReport.ts#L97

But since the first thing chromium gets directed to load is http://0:5601/basepath/bootstrap.js which then errors, the fix might not be a simple one (other than requiring server.rewriteBasePath is set to true)

**Comment by zhongnansu** [comment]
I thought `server.rewriteBasePath` by default is true? https://github.com/elastic/kibana/blob/a0b793698735eb1d0ab1038f8e5d7a951524e929/config/kibana.yml#L18

**Comment by zhongnansu** [comment]
> I tried modifying the relativeUrl code to strip the basepath
> https://github.com/opendistro-for-elasticsearch/kibana-reports/blob/dev/kibana-reports/server/routes/lib/createReport.ts#L97
> 
> But since the first thing chromium gets directed to load is http://0:5601/basepath/bootstrap.js which then errors, the fix might not be a simple one (other than requiring server.rewriteBasePath is set to true)

I thought `server.rewriteBasePath` by default is true? https://github.com/elastic/kibana/blob/a0b793698735eb1d0ab1038f8e5d7a951524e929/config/kibana.yml#L18

**Comment by ccottam** [comment]
based on the docs and the behaviour that isn't the case

The 6.8 docs suggest that the plan was to default to true from 7.
https://www.elastic.co/guide/en/kibana/6.8/settings.html#server-rewriteBasePath


The 7.10 docs on the other hand default to 'deprecated' which based on the observed behaviour is false + print a warning message at startup
https://www.elastic.co/guide/en/kibana/7.10/settings.html#server-rewriteBasePath

taken from a opendistro 1.13 kibana image with a server.basepath configured but nothing for server.rewritebasepath
```
kibana         | {"type":"log","@timestamp":"2021-03-04T20:19:09Z","tags":["warning","config","deprecation"],"pid":1,"message":"You should set server.basePath along with server.rewriteBasePath. Starting in 7.0, Kibana will expect that all requests start with server.basePath rather than expecting you to rewrite the requests in your reverse proxy. Set server.rewriteBasePath to false to preserve the current behavior and silence this warning."}
```

**Comment by zhongnansu** [comment]
This issue has been moved to https://github.com/opensearch-project/dashboards-reports/issues/17
