### ISSUE TITLE
Kibana standalone kibana plugin download url for v1.12.0.0

### ISSUE THREAD

**Issue by Madhan88** [opendistro-for-elasticsearch/kibana-reports#338]
I have elasticsearch and kibana version 7.10.0 so i'm trying to install kibana reports plugin.
For Kibana version 7.10.0, the compatible plugin version is v1.12.0.0 so I need url to download the reporting plugin.Can someone please share the url?

**Comment by zhongnansu** [comment]
Hi you need to install different `kibana-reports` artifacts accroding to your OS and architecture. The links are provided [here](https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/plugins/#reports-kibana) for the latest v1.13.0.0. But for v1.12.0.0, the install link is slightly different

```
# x86 Linux
sudo bin/kibana-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-reports/linux/x64/opendistroReportsKibana-1.12.0.0.zip
# ARM64 Linux
sudo bin/kibana-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-reports/linux/arm64/opendistroReportsKibana-1.12.0.0.zip
# x86 Windows
sudo bin/kibana-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-reports/windows/x64/opendistroReportsKibana-1.12.0.0.zip
```

Also, don't forget to install `reports-scheduler` together with `kibana-reports` to make the feature work. 
https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#reports-scheduler
