### ISSUE TITLE
Support sending compiled report over email/slack

### ISSUE THREAD

**Issue by ThisIsQasim** [opendistro-for-elasticsearch/kibana-reports#339]
~~The documentation for this plugin is missing instructions on how to setup email and slack recipients.~~

We use this plugin to generate a daily PDF of the health status of our backend services. It would be great if these reports could be automatically sent to relevant stakeholders over email or slack etc.

**Comment by zhongnansu** [comment]
The notification feature is currently not available. But it's on our roadmap for sure

**Comment by ThisIsQasim** [comment]
Oh. I thought it had been implemented since the original feature request mentioned reports via email/slack. Should I rename the issue?

**Comment by zhongnansu** [comment]
Can you rename it something more like a feature request? It would be even better if you can provide more details of the use case that you expect. Thx

**Comment by ThisIsQasim** [comment]
I have updated this issue with the feature request and details of the use case.

**Comment by brian-grabau** [comment]
O just found out reports don't have email option, while on a call with large group of users, and the pitchforks came out!!! Do you have eta in email report feature will be released? needless to say we have high demand for this feature..

**Comment by zhongnansu** [comment]
@brian-grabau Hi, it's glad to know users might be interested in the notification feature. We are targeting probably the next next ODFE release to release notification plugin, as well as integrating with reporting. I'll say somwhere around mid May. Soon we'll update the ODFE roadmap in github with the community

**Comment by iget-master** [comment]
Snce this feature is not available, the readme of this plugin should be changed:

> The feature is present in the Dashboard, Discover, and Visualization tabs. Scheduled reports can be sent to (shared with) self or various stakeholders within the organization such as, including but not limited to, executives, managers, engineers (developers, DevOps, IT Engineer) in the form of pdf, hyperlinks, csv, excel via various channels such as email, slack, Amazon Chime.

**Comment by zhongnansu** [comment]
This issue is moved to https://github.com/opensearch-project/dashboards-reports/issues/18
