### ISSUE TITLE
PNG / PDF / CSV Report Generate Issue

### ISSUE THREAD

**Issue by luffy1947** [opendistro-for-elasticsearch/kibana-reports#340]
Dear Team,

We are new to Wazuh, recently we implmeneted on our company . While try to generate report from kibana, we are getting error.

"Download Error"

Appreciate your support. 

![kibana_report_error](https://user-images.githubusercontent.com/48924156/110307750-4550ca80-8025-11eb-882f-cf084b695ec0.png)

**Comment by francisco-hoo** [comment]
Hey @luffy1947, could you please share more details about, such kibana logs?

**Comment by mxmorin** [comment]
I had this error too with query migrated from 6.8 version.
In the error log : 
`{"type":"log","@timestamp":"2021-03-17T09:22:37Z","tags":["error","plugins","opendistroReportsKibana"],"pid":61598,"message":"Failed to generate report: Not Found :: {\"path\":\"/.kibana/_doc/index-pattern%3Aab8da130-78aa-11e9-ba7d-37bf777999b1\",\"query\":{},\"statusCode\":404,\"response\":\"{\\\"_index\\\":\\\".kibana_82110_sit_2\\\",\\\"_type\\\":\\\"_doc\\\",\\\"_id\\\":\\\"index-pattern:ab8da130-78aa-11e9-ba7d-37bf777999b1\\\",\\\"found\\\":false}\"}"}
{"type":"log","@timestamp":"2021-03-17T09:22:37Z","tags":["error","plugins","opendistroReportsKibana"],"pid":61598,"message":"{ Error: Not Found\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/lodash/lodash.js:4949:19)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  status: 404,\n  displayName: 'NotFound',\n  message: 'Not Found',\n  path:\n   '/.kibana/_doc/index-pattern%3Aab8da130-78aa-11e9-ba7d-37bf777999b1',\n  query: {},\n  body:\n   { _index: '.kibana_82110_sit_2',\n     _type: '_doc',\n     _id: 'index-pattern:ab8da130-78aa-11e9-ba7d-37bf777999b1',\n     found: false },\n  statusCode: 404,\n  response:\n   '{\"_index\":\".kibana_82110_sit_2\",\"_type\":\"_doc\",\"_id\":\"index-pattern:ab8da130-78aa-11e9-ba7d-37bf777999b1\",\"found\":false}',\n  toString: [Function],\n  toJSON: [Function] }"}
`
Re-saving the query maked it working
