### ISSUE TITLE
Negative values not exported correctly

### ISSUE THREAD

**Issue by melvinkokxw** [opendistro-for-elasticsearch/kibana-reports#344]
Issue occurred when generating CSV file from a table in Discover. Negative numbers appear in the csv with an extra `'` in front of them. This is what it looks like:

Negative value | Positive value
-- | --
'-47 | 520
'-15 | 475

For reference, this field is of type `number`

**Comment by zhongnansu** [comment]
We'll look into this issue, and keep you updated, thx.

**Comment by zhongnansu** [comment]
This issue is moved to https://github.com/opensearch-project/dashboards-reports/issues/20
