### ISSUE TITLE
Linux releases

### ISSUE THREAD

**Issue by hashworks** [opendistro-for-elasticsearch/kibana-reports#347]
Hi,

Could you provide linux versions in [releases](https://github.com/opendistro-for-elasticsearch/kibana-reports/releases)? Currently, you only provide MacOSX Packages.

Other plugins like [anomaly-detection](https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/releases) provide those and are installable over `kibana/src/cli_plugin install <url>`.

**Comment by zhongnansu** [comment]
Currently if you want to install a released standalone plugin, you can use the cloudfront links we provided. Refer to #338 for those links. Thanks
