### ISSUE TITLE
Adding i18n translations

### ISSUE THREAD

**Issue by starcatter** [opendistro-for-elasticsearch/kibana-reports#348]
Hi,
From what I see in the code most strings are hardcoded in english. Is there any ongoing work to add i18n translation support to this plugin?
If I were to do this myself, completely or partially (ie. just critical user-facing parts), can I submit a pull request? Aside from general contribution guidelines, is there anything I should be aware of when trying to implement that?

**Comment by zhongnansu** [comment]
Hi you are very welcome to post PRs and our team will review those and provide help that you need. As for suggestion, I found something online which I believe you have also read. https://www.elastic.co/guide/en/kibana/current/external-plugin-localization.html

**Comment by zhongnansu** [comment]
This issue has been migrated to https://github.com/opensearch-project/dashboards-reports/issues/46
