### ISSUE TITLE
Time Range not using Commonly Used Ranges from Kibana Settings

### ISSUE THREAD

**Issue by iget-master** [opendistro-for-elasticsearch/kibana-reports#351]
Currently, the `time_range` component uses a constant from `report_settings_constants.tsx` to feed the `commonlyUsedRanges` property of `EuiSuperDatePicker` inside it.

This is not the default behavior across Kibana. The default behavior is to load this from `uiSettings` service, allowing the user to override the available options.

I'm proposing this change that is not a breaking change but a "fix" that makes this plugin follow the default behavior across Kibana.

**Comment by iget-master** [comment]
Although my PR #352 fixes this, this plugin does not support relative dates (see #353). :disappointed:

**Comment by zhongnansu** [comment]
This issue has been moved to https://github.com/opensearch-project/dashboards-reports/issues/41
