### ISSUE TITLE
Time Range not working properly with relative dates

### ISSUE THREAD

**Issue by iget-master** [opendistro-for-elasticsearch/kibana-reports#353]
Steps to reproduce:

1. Create a report definition 
2. On time range field, use relative ranges eg. "from 7 days ago (round)" and "to now".
3. Save the report definition
4. Reopen it a minute later

Note that since internally the KibanaReports plugin converts the range field from elasticsearch DateMath to ISO duration, it is not able to do some things, for example the "round" option won't work properly.

Since I'm working on a lot of issues that I found on this plugin, reading the code I noticed that it don't use DateMath to store the time range of the report. This makes no sense because ISO duration will not be able to represent the same range selected on the default `EuiSuperDatePicker`.

I really see no reason for not using DateMath to store the range:

```
{
  from: "now/d-7d",
  to: "now"
}
```

**Comment by iget-master** [comment]
Also reading the code, there's a ton of complexity on a relatively simple thing.

1. Why is invalid setting a time range in the future? (for example, from -7d to +7d) Setting this range on the dashboard will just work fine (no results in the future probably, but sometimes a index may contain dates in the future)
2. Why use ISO duration instead of DateMath?
3. Why not use the commonly used ranges from the Kibana settings (I've fixed it on #351)

Maybe I'm not seeing some issue solved with this decisions, but looks like just a bad code design.

**Comment by zhongnansu** [comment]
@davidcui-amzn could you help take a look as well, I thought we support relative date range. And we have removed something we couldn't support from the Datepicker

**Comment by iget-master** [comment]
I've spent some hours reading this code, but didn't checked it history of commits. But in the current  branch this is the behavior if I understood correctly:

When saving the Report Definition, the relative range in Elasticsearch's DateMath format (something like `now/d-7d`~`now`) is converted to an ISO duration format: PT168H (Period of 7*24 hours), but the start of this period is not saved (or is not used).

When generating the report, it uses the current timestamp + ISO duration format.

This have some problems:

1. When using absolute dates, it will convert it to a range that is not absolute, and will change at every report generation. IMO, if I set a time range with absolute dates, it should remain absolute
2. Converting DateMath to a duration is not precise, for example: `now+1M/M` will get current month, add a month and round to it start (or end). Trying to to this with duration is impossible, and I will never archieve "Last month" precisely, since depending on the month we have 30 or 31 days.

**Comment by iget-master** [comment]
@zhongnansu Could you please move this issue to the `opensearch-project/dashboards-reports` repository? The https://github.com/opensearch-project/dashboards-reports/pull/49 depends on this being fixed to be merged out.

**Comment by zhongnansu** [comment]
> I've spent some hours reading this code, but didn't checked it history of commits. But in the current branch this is the behavior if I understood correctly:
> 
> When saving the Report Definition, the relative range in Elasticsearch's DateMath format (something like `now/d-7d`~`now`) is converted to an ISO duration format: PT168H (Period of 7*24 hours), but the start of this period is not saved (or is not used).
> 
> When generating the report, it uses the current timestamp + ISO duration format.
> 
> This have some problems:
> 
> 1. When using absolute dates, it will convert it to a range that is not absolute, and will change at every report generation. IMO, if I set a time range with absolute dates, it should remain absolute
> 2. Converting DateMath to a duration is not precise, for example: `now+1M/M` will get current month, add a month and round to it start (or end). Trying to to this with duration is impossible, and I will never archieve "Last month" precisely, since depending on the month we have 30 or 31 days.

@iget-master Before moving this issue, let's discuss more here since we have the context.
1. We assume the scheduled report to be always using a current timestamp + timerange. Even if you select absolute dates, we calculate the range to ISO standard. It doesn't remain absolute. Is there a use case that you feel like we should keep it absolute?
2. The way we convert datemath to ISO is first use `datemath.parse()` function to parse to moment object and do a diff, do you think this is not accurate?
```
timeRange.timeFrom = dateMath.parse(start);
    timeRange.timeTo = dateMath.parse(end);
    const timeDuration = moment.duration(
      dateMath.parse(end).diff(dateMath.parse(start))
    );
```

Also I have another question, you said #352 is depending on this being fixed? I was under the impression that #352 is a fix but doesn't introduce new issues, can we merge in #352 since it's approved?

**Comment by iget-master** [comment]
No, I don't think that #352 can be merged without this being fixed. Because having this fixed will create an inaccurate report. Saying that #352 introduces a bug is not correct, it just exposes an existing bug (note that this issue can be reproduced without the scheduled report)

**Comment by iget-master** [comment]
Replying to:

1. With absolute dates the ISO Period should work
2. It's not accurate because it's impossible to represent some Datemath expressions with Initial date + period.

IMO this functionality is completely broken for most real use cases.

**Comment by zhongnansu** [comment]
This issue has been moved to https://github.com/opensearch-project/dashboards-reports/issues/61, I feel like we need more discussion
