### ISSUE TITLE
Managing authentication for the reporting plugin 

### ISSUE THREAD

**Issue by ubais7** [opendistro-for-elasticsearch/kibana-reports#357]
I'm using Basic elastic & Kibana and only added reporting plugin to kibana.

Since the security module is from elastic itself, how can I configure this credentials to reporting plugin?

**Comment by zhongnansu** [comment]
You also need the reports-scheduler plugin(ES plugin) to make the reporting feature work, there's no credentials that are specific to reporting plugin. All security are managed by security plugin.

**Comment by ubais7** [comment]
Reporting features working fine by adding all documented plugins.

The problem now is, since the kibana&es authentications are enabled through elastic xpack security- reporting plugin was showing authentication errors.

Once I disabled authentication in Kibana & ES , it's working fine.

**Comment by zhongnansu** [comment]
@ubais7 X-pack is not someting we aims to support, x-pack code is not under Apache 2.0 liscense as we do. I'd recommend you check out the ODFE security plugin solution
