### ISSUE TITLE
open distro kibana reporting plugin

### ISSUE THREAD

**Issue by vishalrijhwani** [opendistro-for-elasticsearch/kibana-reports#359]
HI Open distro Team,
                                   I am using kibana 7.11.1, I need kibana reporting plugin for same version i.e 7.11.1, current kibana reporting plugin supports kibana till version 7.10.2, Please inform me when this plugin will be available or what i should do to make current kibana reporting plugin compatible with kibana version 7.11.1

**Comment by vishalrijhwani** [comment]
Further more I am interested in developing open source kibana plugin. I request you to please send me complete detail document with example showing how to develop kibana plugin. Please also give details of tools required to develop kibana plugin

**Comment by zhongnansu** [comment]
Hi, we just announced the release of [OpenSearch](https://github.com/opensearch-project/dashboards-reports), ODFE will not have major release from now on. Reporting is also migrated under OpenSearch and the repo is public. The release will follow OpenSearch version instead of Elasticsearch.
