### ISSUE TITLE
Missing fields in the generated file

### ISSUE THREAD

**Issue by uzhinskiy** [opendistro-for-elasticsearch/kibana-reports#363]
I am trying to create a CSV report based on a saved search that contains fields like **@timestamp, A, B, C.D, C.E, F**, etc. But the generated file only contains **@timestamp, A, B, F** - in the report all complex fields are missing. 
In fact - the fields that mapped as _object_ in my index are missed.
Why did this happen and how can I fix it?

Kibana v 7.10.0 from docker-image "amazon/opendistro-for-elasticsearch-kibana:1.12.0"

**Comment by zhongnansu** [comment]
Could you be more specific about "complex fields", also it's better if you can provide some example, screenshot, dataset you used, anything

**Comment by uzhinskiy** [comment]
For example:
```
   {
        "_index" : "my_index",
        "_type" : "_doc",
        "_id" : "789be064-0758-4245-8ca1-6570df3bb5a7",
        "_score" : 1.0,
        "_source" : {
          "status" : "alert",     -   simple field = string
          "issue_uid" : 123,   -   simple field = number
          "created_at" : "2020-09-21T05:02:48.000+03:00",    -   simple field = date
          "alerts_count" : 2,   -   simple field = number
          "labels" : {       -   complex field = object 
            "kubernetes" : "cluster.k8s",    -  part of complex field  -  will be missed from CSV-report
            "statefulset" : "sts1"  -  part of complex field  -  will be missed from CSV-report
          }
        }
    }

```

**Comment by zhongnansu** [comment]
This issue has been moved to https://github.com/opensearch-project/dashboards-reports/issues/43
