### ISSUE TITLE
Reporting PDF is getting generated  as a single page in version 13.1.0.1. 

### ISSUE THREAD

**Issue by Kanmanir** [opendistro-for-elasticsearch/kibana-reports#376]
## **Reporting PDF is getting generated  as a single page in version 13.1.0.1.** 
[On_demand_report_2021-06-03T06_11_17.128Z_81dff880-c432-11eb-ae0e-8d3c524dd195.pdf](https://github.com/opendistro-for-elasticsearch/kibana-reports/files/6589646/On_demand_report_2021-06-03T06_11_17.128Z_81dff880-c432-11eb-ae0e-8d3c524dd195.pdf)

I have created a setup with odfe-opendistro and trying to generate on-demand and schedule reports for dashboards,
what I observed is the PDF is generated as a single page, when tries to print the pdf visuals size will be as its trying to fit all visuals from dashboard on single page, 
here I have attached a PDF for your reference, 
How can we generate proper PDF with proper visual size.

**Comment by zhongnansu** [comment]
@Kanmanir 1 page is our only solution for pdf. Do you feel like there's a use case that the multi-page pdf is useful? How do you want the page to be splited by? By each individual visualization items?

Please submit a **feature request** to our latest [repo](https://github.com/opensearch-project/dashboards-reports) in OpenSearch. This Open Distro project will not have major feature release in the future, we have migrated to OpenSearch and are slowly deprecating OpenDistro.
