### ISSUE TITLE
Add xpack.reporting.csv.maxSizeBytes to allow larger CSV reports

### ISSUE THREAD

**Issue by ky-ma** [opendistro-for-elasticsearch/kibana-reports#378]
Adding xpack.reporting.csv.maxSizeBytes to kibana.yml fails to load because it's an unrecognized key.

Please add this to next release so we can increase the size of the CSV file in the reports.

`{"type":"log","@timestamp":"2021-06-04T21:19:35Z","tags":["fatal","root"],"pid":7733,"message":"{ Error: Unknown configuration key(s): \"xpack.reporting.csv.maxSizeBytes\". Check for spelling errors and ensure that expected plugins are installed.\n    at ensureValidConfiguration (/usr/share/kibana/src/core/server/legacy/config/ensure_valid_configuration.js:42:11) code: 'InvalidConfig', processExitCode: 64, cause: undefined }`

**Comment by zhongnansu** [comment]
@ky-ma 
There is a related issue but in the new repo. https://github.com/opensearch-project/dashboards-reports/issues/34
Since we have migrated to Opesearch. Could you move the dicussion over there?
