### ISSUE TITLE
_opendistro Index exception

### ISSUE THREAD

**Issue by priyub20** [opendistro-for-elasticsearch/kibana-reports#380]
I have installed kibana-reports plugin ( version 1.13.2.0 ) on kibana - 7.10.2.
While creating report, it is giving below exception in logs:

 `{"type":"log","@timestamp":"2021-06-12T11:27:59Z","tags":["error","plugins","opendistroReportsKibana"],"pid":7,"message":"{ Error: [invalid_index_name_exception] Invalid index name [_opendistro], must not start with '_', '-', or '+', with { index_uuid=\"_na_\" & index=\"_opendistro\" }\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/lodash/lodash.js:4949:19)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  status: 400,\n  displayName: 'BadRequest',\n  message:\n   '[invalid_index_name_exception] Invalid index name [_opendistro], must not start with \\'_\\', \\'-\\', or \\'+\\', with { index_uuid=\"_na_\" & index=\"_opendistro\" }',\n  path: '/_opendistro/_reports/on_demand',\n  query: {},\n  body:\n   { error:\n      { root_cause: [Array],\n        type: 'invalid_index_name_exception',\n        reason:\n         'Invalid index name [_opendistro], must not start with \\'_\\', \\'-\\', or \\'+\\'',\n        index_uuid: '_na_',\n        index: '_opendistro' },\n     status: 400 },\n  statusCode: 400,\n  response:\n   '{\"error\":{\"root_cause\":[{\"type\":\"invalid_index_name_exception\",\"reason\":\"Invalid index name [_opendistro], must not start with \\'_\\', \\'-\\', or \\'+\\'\",\"index_uuid\":\"_na_\",\"index\":\"_opendistro\"}],\"type\":\"invalid_index_name_exception\",\"reason\":\"Invalid index name [_opendistro], must not start with \\'_\\', \\'-\\', or \\'+\\'\",\"index_uuid\":\"_na_\",\"index\":\"_opendistro\"},\"status\":400}',\n  toString: [Function],\n  toJSON: [Function] }"}`

Dockerfile for creating image : 
```
FROM docker.elastic.co/kibana/kibana:7.10.2
USER root
RUN yum update -y && yum install -y unzip
RUN yum install -y libnss3.so xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils \ 
                         xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc fontconfig freetype

#Download chromium from https://github.com/opendistro-for-elasticsearch/kibana-reports/releases 
COPY chromium-linux-x64-with-dependencies.zip /opt/ 
RUN unzip /opt/chromium-linux-x64-with-dependencies.zip -d /opt/chromium
RUN export PATH=$PATH:/opt/chromium/
USER kibana 
RUN bin/kibana-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-reports/linux/x64/opendistroReportsKibana-1.13.2.0-linux-x64.zip

```

**Comment by zhongnansu** [comment]
Hi we just migrated to opensearch and have the release-candidate version available, could you try there? Since we are deprecating this OpenDistro project.

- https://opensearch.org/downloads.html
- https://github.com/opensearch-project/dashboards-reports
