### ISSUE TITLE
plugin fails to run after installed to kibana

### ISSUE THREAD

**Issue by zhongnansu** [opendistro-for-elasticsearch/kibana-reports#40]
**Issue Description**

After `yarn build` generate the distribution `.zip` file, I tried to install to `kibana` by

```
./bin/kibana-plugin install file:///Users/szhongna/Desktop/reporting/kibana/plugins/kibana-reports/build/opendistro_kibana_reports-0.0.1.zip
``` 

However, when I run `./bin/kibana`, it throws the following error.

**error log**
```
  log   [23:43:59.931] [warning][plugins-discovery] Expect plugin "id" in camelCase, but found: apm_oss
  log   [23:44:00.891] [info][plugins-service] Plugin "visTypeXy" is disabled.
  log   [23:44:00.926] [fatal][root] { Error: Cannot find module '/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/plugins/opendistro_kibana_reports'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Module.Hook._require.Module.require (/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/node_modules/require-in-the-middle/index.js:51:29)
    at require (internal/modules/cjs/helpers.js:25:18)
    at createPack (/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/src/legacy/plugin_discovery/plugin_pack/create_pack.js:33:18)
    at MapSubscriber.packageJson$.pipe [as project] (/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/src/legacy/plugin_discovery/plugin_pack/create_pack.js:66:11)
    at MapSubscriber._next (/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/node_modules/rxjs/internal/Subscriber.js:66:18)
    at RefCountSubscriber.Subscriber._next (/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/node_modules/rxjs/internal/Subscriber.js:89:26)
    at RefCountSubscriber.Subscriber.next (/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Subject.next (/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/node_modules/rxjs/internal/Subject.js:60:25)
    at ConnectableSubscriber.Subscriber._next (/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/node_modules/rxjs/internal/Subscriber.js:89:26)
    at ConnectableSubscriber.Subscriber.next (/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/node_modules/rxjs/internal/Subscriber.js:66:18)
    at DistinctSubscriber._finalizeNext (/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/node_modules/rxjs/internal/operators/distinct.js:73:30)
    at DistinctSubscriber._useKeySelector (/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/node_modules/rxjs/internal/operators/distinct.js:67:14)
    at DistinctSubscriber._next (/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/node_modules/rxjs/internal/operators/distinct.js:51:18)
    at DistinctSubscriber.Subscriber.next (/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/node_modules/rxjs/internal/Subscriber.js:66:18) code: 'MODULE_NOT_FOUND' }

 FATAL  Error: Cannot find module '/Users/szhongna/Downloads/kibana-7.8.0-darwin-x86_64/plugins/opendistro_kibana_reports'
```

**Comment by sirmordred** [comment]
@akbhatta @davidcui-amzn @zhongnansu I also compiled "kibana-reports" plugin (latest dev branch) from sources and installed it as a zip, but i hit the exact same error --> FATAL  Error: Cannot find module /usr/share/kibana/plugins/opendistro_kibana_reports

Any news or workaround to solve it?

Note: I just compiled and installed "kibana-reports" plugin to kibana, i didnt install notification nor scheduler plugin, but kibana-reports doesnt seem to have dependency on them? or am i wrong? Thanx

**Comment by zhongnansu** [comment]
> @akbhatta @davidcui-amzn @zhongnansu I also compiled "kibana-reports" plugin (latest dev branch) from sources and installed it as a zip, but i hit the exact same error --> FATAL Error: Cannot find module /usr/share/kibana/plugins/opendistro_kibana_reports
> 
> Any news or workaround to solve it?
> 
> Note: I just compiled and installed "kibana-reports" plugin to kibana, i didnt install notification nor scheduler plugin, but kibana-reports doesnt seem to have dependency on them? or am i wrong? Thanx

After some root cause analysis, I found this issue is related to 2 Kibana issues. Currently after a plugin build, it failed to 
1. https://github.com/elastic/kibana/issues/70412 closed
2. https://github.com/elastic/kibana/issues/70426 open

 
Even though this [PR](https://github.com/elastic/kibana/pull/75019) fixed one issue above, but this fix is targeting a release v7.10.0, and our project is developing under 7.8.0. Besides the second issue is still open.So my suggestion is to follow the workaround they provide in the issues pages. 

First add the kibana.json file to the `.kibana-plugin-helpers.json` file:

```
{
  "buildSourcePatterns": [
    "kibana.json"
  ]
}
```

Then for the second issue above, run the optimizer manually and include the generated files into your plugin .zip:

```
mkdir -p kibana/opendistro_kibana_reports/target/public
cp target/public/* kibana/opendistro_kibana_reports/target/public/
zip -ur build/opendistro_kibana_reports-*.zip kibana/opendistro_kibana_reports/target/public
```
I've tested myself and it worked. Let me know how it goes with you.

**Comment by joshuali925** [comment]
I ran into this issue as well. I think you can include the target folder to avoid the manual step. @zhongnansu  https://github.com/joshuali925/gantt_vis/blob/develop/.kibana-plugin-helpers.json#L8

**Comment by zhongnansu** [comment]
@joshuali925 Thanks! That seems like the best workaround we can provide now, will address in #96

**Comment by sirmordred** [comment]
@zhongnansu thanks so much for the reply, i also applied your latest commit to partially fix the build, it worked but i now hit the "**404 elastic did not load properly**" issue which you mentioned as https://github.com/elastic/kibana/issues/70426 

I tried the manual step you described but it seems there is no file in **target/public/*** 
(im running **yarn kbn bootstrap** and then **yarn build** to build plugin)

Do you have a working plugin zip that i can try?

Thanks
Best regards

**Comment by zhongnansu** [comment]
@sirmordred  Hi, the fact is `target/` will be generated once the plugin is complied and run by the optimizer. Currently Kibana doesn't provide a way to compile 3-rd party plugins solely. That issue is also an open issue, we'll keep an eye on the update.

But there is still a workaround. My suggestion is first checkout the project under a kibana plugins folder(the same as mentioned [here](https://github.com/opendistro-for-elasticsearch/kibana-reports/blob/dev/kibana-reports/README.md#setup)) and after you run `yarn kbn bootstrap`, manually start the project by `yarn start --no-base-path --oss` under kibana path(**not the reporting plugin path**), in case node version is complaining, you could run `nvm use` to fix. Then you'll see a kibana instance running with our plugin built in. You can also start a ES v7.8.0 instance with the reports-scheduler plugin installed, or use `./gradlew run`, which is the ES version of `yarn start --no-base-path`. Or you could build the reports-scheduler plugin yourself and install to an ES instance, since there should be no issue with ES plugin build.

After your kibana is running, you should be able to access the localhost:5601 to play around with the plugin. More important, at this time the `target/` folder will be created. And if you do `yarn build` now, `target/` will be included in the `.zip` file

Please give it a try, good luck : )

**Comment by davidcui-amzn** [comment]
@sirmordred to add onto what Zhongnan has said here, I recommend running `./gradlew run -Drun.distribution=oss` for your ES 7.8.0 instance to ensure you run the open source distribution similarly to Kibana

**Comment by sirmordred** [comment]
@zhongnansu @davidcui-amzn  Thanx so much, it finally worked

and also im using it with opendistro kibana&opendistro ES in dockerized environment

I tried to create report through gui after installing plugin but it failed for some reason

`{"type":"log","@timestamp":"2020-09-25T09:09:50Z","tags":["error","plugins","opendistroKibanaReports"],"pid":1,"message":"**Failed to generate report by id: Error: Could not find browser revision 800071. Run \"PUPPETEER_PRODUCT=firefox npm install\" or \"PUPPETEER_PRODUCT=firefox yarn install\" to download a supported Firefox browser binary.**"}

{"type":"log","@timestamp":"2020-09-25T09:09:50Z","tags":["error","http"],"pid":1,"message":"Error: options.statusCode is expected to be set. given options: undefined\n    at Object.custom (/usr/share/kibana/src/core/server/http/router/response.js:259:13)\n    at errorResponse (/usr/share/kibana/plugins/opendistro_kibana_reports/server/routes/utils/helpers.js:47:19)\n    at _callee2$ (/usr/share/kibana/plugins/opendistro_kibana_reports/server/routes/report.js:144:49)\n    at tryCatch (/usr/share/kibana/plugins/opendistro_kibana_reports/node_modules/regenerator-runtime/runtime.js:63:40)\n    at Generator.invoke [as _invoke] (/usr/share/kibana/plugins/opendistro_kibana_reports/node_modules/regenerator-runtime/runtime.js:293:22)\n    at Generator.throw (/usr/share/kibana/plugins/opendistro_kibana_reports/node_modules/regenerator-runtime/runtime.js:118:21)\n    at asyncGeneratorStep (/usr/share/kibana/plugins/opendistro_kibana_reports/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n    at _throw (/usr/share/kibana/plugins/opendistro_kibana_reports/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}

{"type":"error","@timestamp":"2020-09-25T09:09:49Z","tags":[],"pid":1,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toInternalError (/usr/share/kibana/src/core/server/http/router/response_adapter.js:69:19)\n    at Router.handle (/usr/share/kibana/src/core/server/http/router/router.js:163:34)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/api/reporting/generateReport/-hmGxHQB7y2SrJzli9wO","path":"/api/reporting/generateReport/-hmGxHQB7y2SrJzli9wO","href":"/api/reporting/generateReport/-hmGxHQB7y2SrJzli9wO"},"message":"Internal Server Error"}

{"type":"response","@timestamp":"2020-09-25T09:09:49Z","tags":[],"pid":1,"method":"post","statusCode":500,"req":{"url":"/api/reporting/generateReport/-hmGxHQB7y2SrJzli9wO","method":"post","headers":{"host":"10.255.1.136:5601","connection":"keep-alive","content-length":"0","kbn-version":"7.8.0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","content-type":"application/json","accept":"*/*","origin":"http://10.255.1.136:5601","referer":"http://10.255.1.136:5601/app/opendistro_kibana_reports","accept-encoding":"gzip, deflate","accept-language":"tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7","securitytenant":"__user__"},"remoteAddress":"10.255.1.44","userAgent":"10.255.1.44","referer":"http://10.255.1.136:5601/app/opendistro_kibana_reports"},"res":{"statusCode":500,"responseTime":167,"contentLength":9},"message":"POST /api/reporting/generateReport/-hmGxHQB7y2SrJzli9wO 500 167ms - 9.0B"}`

I only installed kibana-reports plugin to opendistro kibana, didnt installed scheduler nor other plugin to kibana/ES

Is there any other dependencies that must be installed to kibana or ES for reporting plugin to work correctly?

**Comment by sirmordred** [comment]
EDIT: ahh i see now, @zhongnansu my issue is probably related with step 4 in your comment

> Last step before you do yarn build, kibana-helper v7.8.0 failed to pick up any hidden files with a dot prefix, so it won't pick up the chromium that downloaded and add to the puppeteer package under .local-chromium. See issues here https://discuss.elastic.co/t/kibana-plugin-build-and-local-chromium/235148/4 and there is a one line fix in v7.8.1 Kibana, which we can manually fix now. https://github.com/elastic/kibana/pull/68247/files

**Comment by nullptr34** [comment]
Hi @davidcui-amzn and @zhongnansu , first of all big thanx to you for your awesome reporting plugin and development, it is really nice

I was also playing it with my dockerized OD elastic&kibana environment, there is also missing library(libatk.so) dependency problem on dockerized opendistro-kibana-1.10.1, i fixed it by installing the following libs
`RUN yum -y install pango.x86_64 pango-devel.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 \
 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 \
 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 \
 pixman.x86_64 pixman-devel.x86_64 cairo.x86_64 cairo-devel.x86_64 libjpeg-turbo.x86_64 libjpeg-turbo-devel.x86_64 \
 ipa-gothic-fonts cabextract xorg-x11-utils xorg-x11-font-utils fontconfig \
 xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc \
 open-sans-fonts liberation-fonts`

everything is good but when i clicked to e.g "Download PDF" button to generate and download report, it fails with the following error log
`{"type":"log","@timestamp":"2020-10-03T14:43:55Z","tags":["error","plugins","opendistroKibanaReports"],"pid":1,"message":"500 [security_exception] Unexpected exception indices:data/read/get"}`

in the OD ES similar error log appears
`[WARN ][r.suppressed             ] [elasticsearch] path: /_opendistro/reports_scheduler/job, params: {index=_opendistro, id=job, type=reports_scheduler}
org.elasticsearch.ElasticsearchSecurityException: Unexpected exception indices:data/read/get
	at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply0(OpenDistroSecurityFilter.java:299) [opendistro_security-1.10.1.0.jar:1.10.1.0]
	at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityFilter.apply(OpenDistroSecurityFilter.java:138) [opendistro_security-1.10.1.0.jar:1.10.1.0]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:177) [elasticsearch-7.9.1.jar:7.9.1]`

Is there any other changes need to be done on Opendistro-kibana or opendistro-es?
like adding security access policy to maybe security_rules.yml(?)

I just compiled and installed reporting plugin, and installed as zip on top of opendistro-kibana-1.10.1 official docker image
didnt compiled nor installed scheduler plugin

**Comment by zhongnansu** [comment]
@nullptr34 
Currently we haven't integrated with security plugin yet, we are working towards that. If you uninstall or disable the security plugin, I believe it should work fine. We will create a separate issue to track security.
