### ISSUE TITLE
Move plugin to new kibana platform.

### ISSUE THREAD

**Issue by mihirsoni** [opendistro-for-elasticsearch/kibana-reports#6]
We should move this kibana plugin to latest platform and no support for legacy.

**Comment by zhongnansu** [comment]
server    log   [05:20:51.457] [warning][legacy-service] Some installed third party plugin(s) [example_plugin] are using the legacy plugin format and will no longer work in a future Kibana release. Please refer to https://ela.st/kibana-breaking-changes-8-0 for a list of breaking changes and https://ela.st/kibana-platform-migration for documentation on how to migrate legacy plugins.
