### ISSUE TITLE
Support future date for scheduling a report

### ISSUE THREAD

**Issue by zhongnansu** [opendistro-for-elasticsearch/kibana-reports#65]
Currently there is only support for scheduling a job based on "internval" (recurring) and "cron" (cron based). 

User should be able to schedule a report on exact future date. This is currently limited by the OD job-scheduler SPI we use, which only support interval and cron.

**Comment by davidcui-amzn** [comment]
@zhongnansu Can we close this issue now?

**Comment by zhongnansu** [comment]
> @zhongnansu Can we close this issue now?

@davidcui-amzn This feature is not implemented yet. Currently we only have `daily` and `By interval` working as expected
