### ISSUE TITLE
Schema for header and footer

### ISSUE THREAD

**Issue by davidcui-amzn** [opendistro-for-elasticsearch/kibana-reports#68]
Currently header and footer in the report definitions are not included in the schema, so the header and footer values are placeholders in the server-side. 

We want to add `header` and `footer` fields in the report definition schema so that we no longer have to use these placeholder values, as well as add any server-side parsing needed for the markdown.

**Comment by zhongnansu** [comment]
#59

**Comment by zhongnansu** [comment]
Added and improved in
#120 
#123 
#125
